### ISSUE TITLE
module 'ctypes' has no attribute 'windll'

### ISSUE THREAD

**Issue by NicTanghe** [hkaramian/RobustVideoMatting-For-Nuke#8]
❯ Exception in thread Thread-7 (run_rvm_core):
Traceback (most recent call last):
  File "/home/tanghe/tools/Nuke15.0v4/lib/python3.10/threading.py", line 1016, in _bootstrap_inner
    self.run()
  File "/home/tanghe/tools/Nuke15.0v4/lib/python3.10/threading.py", line 953, in run
    self._target(*self._args, **self._kwargs)
  File "<string>", line 51, in run_rvm_core
AttributeError: module 'ctypes' has no attribute 'windll'

**Comment by NicTanghe** [comment]
ah, OK it seems that that is because the function is windows specific, and I am on Linux.
Weird that a library would not be platform-agnostic.

**Comment by NicTanghe** [comment]
This doesn’t happen when I render smaller frame ranges.
Also, pressing Open DIR doesn't do anything.
